### ISSUE TITLE
Bracket coloring in Lua files

### ISSUE THREAD

**Issue by zeitchef** [rmehri01/onenord.nvim#1]
I've been waiting for someone to merge these two color palettes, so thanks!

I've noticed that matching braces `{}` are colored differently in some files (yellow in Lua - see screenshot), as opposed to JavaScript files for instance. Is that intentional?

<img width="493" alt="Screen Shot 2021-10-30 at 23 53 21" src="https://user-images.githubusercontent.com/6670659/139559376-35d68ac0-33fb-46e7-a785-f4195ad9016f.png">

If so, is there a way to override this behavior to have uniformity across all filetypes? Thanks!

**Comment by rmehri01** [comment]
No problem, I'm glad you like it! I believe that is intentional due to them being different in tree sitter. In Lua they are constructors while in JavaScript they are delimiters:

https://github.com/rmehri01/onenord.nvim/blob/73aef7f22d42dcc3d96797d2c1e61c653dec2598/lua/onenord/theme.lua#L369-L370

https://github.com/rmehri01/onenord.nvim/blob/73aef7f22d42dcc3d96797d2c1e61c653dec2598/lua/onenord/theme.lua#L412-L417

I think that you can override `TSConstructor` using vim's highlight but I could provide a more convenient way to do it in Lua as a part of the config options if you think that would be helpful!

**Comment by rmehri01** [comment]
I went ahead and added a way to overwrite any of the highlight groups so you can give it a try if you'd like.

**Comment by zeitchef** [comment]
Thanks for the quick response @rmehri01 - unfortunately, this is still not overwriting `TSConstructor` for me.

```
  use {
    'rmehri01/onenord.nvim',
    setup = function()
      local colors = require 'onenord.colors'

      require('onenord').setup {
        custom_highlights = {
          TSConstructor = { fg = colors.dark_blue },
        },
      }
    end,
  }
```

Have I just overlooked something?

**Comment by rmehri01** [comment]
Hey @zeitchef, I think you need to use `config =` rather than `setup =`. When I try it, `setup =` doesn't work since it runs before the plugin is loaded. I'm not sure if `setup =` is supposed to work or not but from what I've seen from other plugins, they seem to use `config =` but correct me if I'm wrong! This works for me:

```lua
use {
  "rmehri01/onenord.nvim",
  config = function()
    local colors = require("onenord.colors")

    require("onenord").setup({
      custom_highlights = {
        TSConstructor = { fg = colors.dark_blue },
      },
    })
  end,
}
```

**Comment by zeitchef** [comment]
Thanks @rmehri01 - you're right, of course. Unfortunately, this somehow doesn't work for my setup. The only way I got it to work was to manually override the highlight:

`vim.highlight.create('TSConstructor', { guifg = onenord.dark_blue }, false)`

**Comment by rmehri01** [comment]
Hmm, I see. If you're okay with that then great but otherwise let me know if I can do anything else and I could give it a shot!
