### ISSUE TITLE
Color Highlighting Issue in NvimTree

### ISSUE THREAD

**Issue by shMorganson** [rmehri01/onenord.nvim#14]
Files that are executable seem to have a green that doesn't match the rest of the theme. This might be my setup but I couldn't find anything in my config. 

![Screen Shot 2021-12-02 at 2 23 06 PM](https://user-images.githubusercontent.com/59580484/144489120-255f4e3b-6bec-4b53-8324-4fadaa3b188c.png)

**Comment by rmehri01** [comment]
Hi, I don't have a highlight for executable files so it should go to the default [described here](https://github.com/kyazdani42/nvim-tree.lua/blob/master/lua/nvim-tree/colors.lua#L38). 

This might be because some other theme is overwriting `vim.g.terminal_color_2`, so I could put these highlights in!

This is what it looks like for me for reference:

![image](https://user-images.githubusercontent.com/52933714/144494234-6e0361d1-6976-4443-a8aa-0435e3bedcde.png)

![image](https://user-images.githubusercontent.com/52933714/144494770-80c85da7-3c17-4f9b-9038-3c1580297713.png)

**Comment by rmehri01** [comment]
I just pushed a commit that should fix it, can you try it out?

**Comment by shMorganson** [comment]
You're the best! All good. I was looking to do it myself and you took care of it so fast! Thank you!!!

**Comment by rmehri01** [comment]
No problem, glad I could help! 😄
