### ISSUE TITLE
[feature request: inverse matches

### ISSUE THREAD

**Issue by quantum-booty** [rmehri01/onenord.nvim#35]
In https://github.com/srcery-colors/srcery-vim there is an option to inverse the colour of matches and match parenthesis of treesitter-highlight module or a / search:
image
image

Could you please add a similar feature to onenord? Because I think this can improve visibility of these matches, as you see its currently a bit hard to see without inverse colours.
image

[](url)

**Comment by rmehri01** [comment]
Hi, I think your images aren't showing up for me but I think I get the idea. Something like this?

<img width="520" alt="image" src="https://user-images.githubusercontent.com/52933714/167968017-33b88997-ece4-4ed1-bc4e-5f3e8b9bb285.png">

It doesn't look as nice for visual mode though since right now there is no foreground:

<img width="519" alt="image" src="https://user-images.githubusercontent.com/52933714/167968406-92d09a72-aff0-4c07-9b63-7593e155456b.png">

Would you want visual/selection to look the same as the match paren one (dark blue on yellow) or do you have something else in mind?

**Comment by quantum-booty** [comment]
Yeah this is exactly I am looking for! How can I reverse the visual selection?

**Comment by rmehri01** [comment]
Yup, I'll add the inversed match paren as an option but I think that the visual one may be less common so I'll leave it out for now!
