### ISSUE TITLE
Support for nvim-navic

### ISSUE THREAD

**Issue by stevanmilic** [rmehri01/onenord.nvim#42]
Add highlights for [nvim-navic ](https://github.com/SmiteshP/nvim-navic#-customise=).

If I find the time, I'll submit a PR 😄

**Comment by rmehri01** [comment]
Hi! I haven't used this plugin so maybe I'm missing something but is there supposed to be any default highlighting? It seems like many of the groups correspond to the treesitter highlights like `TSFunction` or `TSString` so it might be better to define them upstream so that color schemes don't have to repeat them? What do you think?

**Comment by stevanmilic** [comment]
hey @rmehri01, thanks for the quick answer. Yea that does make sense, I'll open a discussion upstream.
