### ISSUE TITLE
FR: setup option to use default nord palette

### ISSUE THREAD

**Issue by manuelcattelan** [rmehri01/onenord.nvim#46]
Hi @rmehri01, I've been rocking this theme for quite a while and it is lovely, so thanks for your hard work!

I was wondering if it would be possible to add an option to override highlight groups to use the default nord color palette without having to do it manually. I think it would be great to just have a quick flag to switch between your implementation and the default one without having to add or remove a lot of override options.

**Comment by rmehri01** [comment]
Hi, thanks for the kind words, I'm glad you like it! I'm not sure how I feel about having a default Nord palette because its not really the purpose of this project and has been done by [https://github.com/shaunsingh/nord.nvim](https://github.com/shaunsingh/nord.nvim). I think it also might not be too much work to use `custom_colors` to define your own palette if you really want to, what are your thoughts?

**Comment by manuelcattelan** [comment]
The only reason for having it all in this plugin was because this allows for much more customisation options, but since I opened this issue I played around with `custom_colors` to achieve that and it wasn’t a hard work at all.

I’m closing the issue, thank you again!
