### ISSUE TITLE
Missing distinction for rust format! named parameters.

### ISSUE THREAD

**Issue by Mekanik** [rmehri01/onenord.nvim#65]
```rust
println!("reading_meta={meta:?}");
```

onenord
<img width="332" alt="image" src="https://user-images.githubusercontent.com/670361/232259255-75281885-6910-4948-ad7f-0a6c963d4825.png">

onedark
<img width="338" alt="image" src="https://user-images.githubusercontent.com/670361/232259275-ff1b041a-a6ba-4b3f-919c-0bc2ec6c945b.png">

nord
<img width="333" alt="image" src="https://user-images.githubusercontent.com/670361/232259264-3904e652-437a-44df-8bbb-c054bfe31f3d.png">

Expectations: `meta` is distinct inside `{meta:?}`.

TS Inspect:
<img width="664" alt="image" src="https://user-images.githubusercontent.com/670361/232259692-fc4a6b8f-02e3-4ee5-ac56-3fc17cb9259d.png">

**Comment by rmehri01** [comment]
Hey, thanks for bringing this up! I was basically following the way that Kanagawa and Tokyonight do the semantic tokens and they set `@lsp.type.variable` to `none` to use the treesitter highlighting instead. Not sure why they do it this way but it seems like in this case treesitter doesn't account for the variable there. I think I can just change it to link to the treesitter `@variable` so that we get this:

<img width="217" alt="Screenshot 2023-04-15 at 6 35 58 PM" src="https://user-images.githubusercontent.com/52933714/232261453-7225fd73-ddf0-4544-91cf-bd2a78f17008.png">

**Comment by Mekanik** [comment]
Thanks for the quick reply and fix! I can confirm the issue is resolved for me.

**Comment by rmehri01** [comment]
No problem!
