### ISSUE TITLE
Issue with matching HTML bracket color in Vue SFC

### ISSUE THREAD

**Issue by zeitchef** [rmehri01/onenord.nvim#7]
I've noticed a little problem with some opening HTML bracket colors being incorrectly set in Vue single-file components (see screenshot). 

In line 3 and 7, the opening angle bracket is colored yellow. If I move my cursor over this line, the color corrects itself. Any ideas what might be happening here?

<img width="651" alt="Screen Shot 2021-11-05 at 11 20 26" src="https://user-images.githubusercontent.com/6670659/140496331-a57b21ee-d3a0-45f1-ad49-a8fbc154dc7f.png">

**Comment by rmehri01** [comment]
Hi again! I don't think this is the color scheme's fault since it seems to happen to me on many different ones (default, one dark, tokyonight, Nord). I think it has to do with tree sitter since doing `:TSBufDisable highlight` seems to fix it. Can you confirm that these are the case for you as well?

<img width="1542" alt="Screen Shot 2021-11-05 at 8 42 17 AM" src="https://user-images.githubusercontent.com/52933714/140538137-e593df64-7f7d-4a0d-8890-53f16c65210f.png">

**Comment by zeitchef** [comment]
Ah, I see. I never noticed this with my previous Nord theme, but this is clearly an upstream problem. Closing.
